### ISSUE TITLE
undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by AndreasBaumgart** [sds/overcommit#700]
When upgrading from 0.51.0 to 0.52.0 and performing a `git push` a ruby error is raised. 

```sh
❯ git push
Running pre-push hooks
Run RSpec test suite..........................................[RSpec] FAILED
Hook raised unexpected error
undefined method `split' for nil:NilClass
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_context/pre_push.rb:21:in `remote_ref_deletion?'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook/pre_push/base.rb:15:in `run?'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_runner.rb:195:in `should_skip?'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_runner.rb:159:in `run_hook'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_runner.rb:97:in `block in consume'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_runner.rb:94:in `loop'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_runner.rb:94:in `consume'
Check for security vulnerabilities.........................[Brakeman] FAILED
Hook raised unexpected error
undefined method `split' for nil:NilClass
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_context/pre_push.rb:21:in `remote_ref_deletion?'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook/pre_push/base.rb:15:in `run?'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_runner.rb:195:in `should_skip?'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_runner.rb:159:in `run_hook'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_runner.rb:97:in `block in consume'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_runner.rb:94:in `loop'
/Users/andreas/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/overcommit-0.52.0/lib/overcommit/hook_runner.rb:94:in `consume'

✗ One or more pre-push hooks failed
```

Here's my `overcommit.yml`:

```yaml
PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail
  EsLint:
    enabled: true
    on_warn: fail
    required_executable: 'npm'
    command: ['npm', 'run', 'lint']
  BundleAudit:
    enabled: true
    flags: ['--update']
  BundleOutdated:
    enabled: true

PrePush:
  RSpec:
    enabled: true
    on_warn: fail
  Brakeman:
    enabled: true
    on_warn: fail

CommitMsg:
  RussianNovel:
    enabled: true
  CapitalizedSubject:
    enabled: false

```

**Comment by sds** [comment]
Thanks for the report! Released [0.52.1](https://github.com/sds/overcommit/releases/tag/v0.52.1) to fix.
